### ISSUE TITLE
Add support for /data partition being mounted or on another drive

### ISSUE THREAD

**Issue by starsoccer** [Nitrux/casper-znx#1]
I am looking for a way to use Nitrux and znx such that all my installed apps and data can be portable. The ideal scenario for me would be that I have 2 or more computers with nitrux OS installed and then a USB drive with my apps and data. I can plug my USB into either of the machines and start using the device as if I had all my apps/data.

From talking with @UriHerrera on gitter it seems like the best way to accomplish this would be to allow the `/data` partition to reside on another separate disk from the OS. While I am not very familiar with Nitrux and how the whole system works, I would assume just being able to mount any device to be used as `/data` would work.

**Comment by luis-lavaire** [comment]
Since [this commit](def6f56) Each image will have its own data directory (see the comment at the bottom of the commit diff).
